version: "3.8"

services:
  consumer:
    build:
      context: ./consumer
    command: air
    env_file:
      - ./consumer/.env
    networks:
      - proyecto-1

  gateway:
    build:
      context: ./gateway
    command: air
    environment:
      - MOM_HOST=resolver
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
    env_file:
      - ./gateway/.env
    networks:
      - proyecto-1

  resolver:
    build:
      context: ./mom
    command: go run ./cmd/resolver/main.go
    environment:
      - PORT=8080
    env_file:
      - ./mom/.env
    networks:
      - proyecto-1

  leader:
    build:
      context: ./mom
    # command: air --target="./cmd/node/main.go"
    command: go run ./cmd/node/main.go
    env_file:
      - ./mom/.env
    environment:
      - PORT=8080
    networks:
      - proyecto-1

  follower-1:
    build:
      context: ./mom
    # command: sleep 15s && air --target="./cmd/resolver/main.go"
    command: go run ./cmd/node/main.go
    env_file:
      - ./mom/.env
    environment:
      - PORT=8080
    networks:
      - proyecto-1

  follower-2:
    build:
      context: ./mom
    # command: sleep 30s && air --target="./cmd/resolver/main.go"
    command: go run ./cmd/node/main.go
    env_file:
      - ./mom/.env
    environment:
      - PORT=8080
    networks:
      - proyecto-1

networks:
  proyecto-1:
