version: "3.8"

services:
  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    command: go run ./consumer/cmd/main.go
    environment:
      - SELF_IP=172.31.87.2
      - MOM_HOST=172.31.89.34
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
    ports:
      - 8080:8080
