version: "3.8"

services:
  consumer:
    build:
      context: ./consumer
    command: air
    env_file:
      - ./consumer/.env
    networks:
      - proyecto-1

  gateway:
    build:
      context: ./gateway
    command: air
    environment:
      - MOM_HOST=resolver
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
    env_file:
      - ./gateway/.env
    networks:

      - proyecto-1
  resolver:
    build:
      context: ./mom
    command: go run ./cmd/resolver/main.go
    environment:
      - PORT=8080
    env_file:
      - ./mom/.env
    networks:
      - proyecto-1

  leader:
    build:
      context: ./mom
    command: go run ./cmd/node/main.go
    environment:
      - RESOLVER_IP=resolver
      - RESOLVER_PORT=8080
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
      - PORT=8080
    networks:
      - proyecto-1
    depends_on:
      - resolver

  follower-1:
    build:
      context: ./mom
    command: go run ./cmd/node/main.go
    environment:
      - RESOLVER_IP=resolver
      - RESOLVER_PORT=8080
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
      - PORT=8080
    networks:
      - proyecto-1
    depends_on:
      - resolver

  follower-2:
    build:
      context: ./mom
    command: go run ./cmd/node/main.go
    environment:
      - RESOLVER_IP=resolver
      - RESOLVER_PORT=8080
      - MOM_PORT=8080
      - CLUSTER_PORT=8080
      - PORT=8080
    networks:
      - proyecto-1
    depends_on:
      - resolver

networks:
  proyecto-1:
